### ISSUE TITLE
Set up location to host operator images

### ISSUE THREAD

**Issue by font** [font/gatekeeper-operator#3]
This issue captures the work needed to set up a place to host operator image(s) on [quay.io](https://quay.io) with a robot account that would handle updating the following images within CI (see #2):
- An image would ideally get updated upon every PR merging, and tagged either as `master` or the commit SHA that triggered it.
- An image that represented the particular release of this operator and tagged both with the release version (e.g. `v0.0.1`) and `latest`.

**Comment by tchughesiv** [comment]
`quay.io/gatekeeper/operator`

this is done w/ https://github.com/font/gatekeeper-operator/pull/21
