### ISSUE TITLE
two steps install experience

### ISSUE THREAD

**Issue by ycao56** [font/gatekeeper-operator#32]
I built bundle and index image and tested the operator on OCP. Currently, the install experience is
1. install gatekeeper operator
2. create gatekeeper CR to create gatekeeper

Is this the experience we want to provide to customer to install gatekeeper?
Is it possible to create the gatekeeper CR by default?

**Comment by font** [comment]
@ycao56 I think so, yes. That is the typical install experience for most operators. That is, the operator CR is the control surface that is exposed to the user to allow them to tweak configuration parameters for their gatekeeper installation. If we install the gatekeeper CR by default, we're going to assume many defaults that the user may or may not want.

While we could certainly create the gatekeeper CR by default, or perhaps provide an option to do so, often times an admin may install an operator to allow any users of the cluster to install the software at their discretion. However, this is more applicable to namespace scoped software.

**Comment by ycao56** [comment]
thanks @font for clarification
closing this
